spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: app-client
          uri: lb://app-client
          predicates:
            - Path=/app-client/**
          filters:
            - StripPrefix=1
        - id: guiyun
          uri: http://guiyunweb.com
          predicates:
            - Path=/guiyun/**
          filters:
            - StripPrefix=1